- name: Create the file to add the current node to the replica set
  template: src=repset_add.j2 dest=/tmp/repset_add.js

- name: Add the current node to the replication set
  shell: /usr/bin/mongo -host {{ groups["mongod_primary"][0] }}:{{ hostvars[groups["mongod_primary"][0]]["mongod_port"] }} /tmp/repset_add.js
  args:
    creates: addNodeToReplicaset
