- name: Create the file to initialize the replicaset
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo /tmp/repset_init.js
  args:
    creates: initiateReplicaset

