- name: Add the admin user to the replicaset
  mongodb_user: database=admin name=admin password={{ mongo_admin_pass }} login_port={{ mongod_port }} roles='root' state=present
  ignore_errors: yes

- name: Create the file to initialize the replicaset
  template: src=repset_init.j2 dest=/tmp/repset_init.js

- name: Initialize the replication set on the primary
  shell: /usr/bin/mongo -u admin -p {{ mongo_admin_pass }} --authenticationDatabase admin /tmp/repset_init.js
  args:
    creates: initiateReplicaset
