---
- name: Write Team member names 
  copy: src=team.txt dest=/root/team.txt

- name: Create the mongod user
  user: name=mongodb 

#- shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
- name: Add 10gen official apt source to sources list
  apt_key: keyserver=keyserver.ubuntu.com id=7F0CEB10
  register: keyserver

- shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/10gen.list
  when: keyserver|changed

- name: apt-get update
  apt: update_cache=yes

- name: Install MondoDB
  apt: name="{{item}}" state=present
  with_items:
    - mongodb-10gen
    - python-pip 
    - python-dev
    - build-essential 
- pip: name=pymongo

- name: Create the necessary directory for the namenode metadata
  file: 
    path: "{{ item }}" 
    owner: mongodb 
    group: mongodb
    state: directory
  with_items:
    - "{{mongodb_datadir}}"
    - "{{mongodb_logdir}}"
    - "{{mongodb_journaldir}}"

    #- lineinfile:
    #dest: /etc/mongodb.conf
    #regexp: "{{item.regexp}}"
    #line: "{{ item.line }}"
    #with_items:
      #  - {regexp: '^logpath',line: 'logpath=/log/mongod.log'}
      #- {regexp: '^logappend',line: 'logappend=true'}
      #- {regexp: '^fork',line: 'fork=true'}
      #- {regexp: '^dbpath',line: 'dbpath=/data'}
      #- {regexp: '^replSet',line: 'replSet=rs'}
      #notify: restart MongoDB

- name: Create the iptables file
  template: src=iptables.j2 dest=/tmp/iptables.rules

- name: Update iptable
  shell: iptables-restore < /tmp/iptables.rules
  args: 
    creates: updateIptable
  notify: restart iptables 

- name: config mongodb
  template: src=mongodb.conf.j2 dest=/etc/mongodb.conf
  notify: restart MongoDB

  #- name: Start MongoDB
  #service:
    #  name: mongodb
    #state: restarted
    #enabled: yes
